# Generated by cucumber-sinatra. (Mon Oct 25 21:26:17 -0600 2010)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'spec'

Capybara.app = App

class AppWorld
  include Capybara
  include Spec::Expectations
  include Spec::Matchers
end

World do
  AppWorld.new
end
